#pragma once

#include "sb6.h"

static const GLchar* vertex_shader_source[] =
{
	"	#version 430 core															\n"
	"																				\n"
	"	layout (location = 0) in vec4 offset;										\n"
	"	layout (location = 1) in vec4 color;										\n"
	"	layout (location = 2) in vec4 eye;											\n"
	"																				\n"
	"	layout (location = 17) uniform mat4 transform_mat;							\n"
	"																				\n"
	"																				\n"
	"	out vec4 vs_color;															\n"
	"																				\n"
	"	void main(void)																\n"
	"	{																			\n"
	"		vec4 vertices[3] = vec4[3] (vec4(0.25, -0.25, 0.5, 1.0), 				\n"
	"										 vec4(-0.25, -0.25, 0.5, 1.0),			\n"
	"										 vec4(0.25, 0.25, 0.5, 1.0));			\n"
	"																				\n"
	"		//mat4 transform_mat = mat4(transform0, transform1, transform2, transform3);		\n"
	"																				\n"
	"		for(int i = 0; i < 3; i++)												\n"
	"		{																		\n"
	"		vertices[i] = transform_mat * vertices[i];								\n"
	"																				\n"
	"		}																		\n"
	"																				\n"
	"		mat4 eye_mat = mat4(vec4(1.0, 0.0, 0.0, 0.0),							\n"
	"							vec4(0.0, 1.0, 0.0, 0.0),							\n"
	"							vec4(0.0, 0.0, 1.0, 0.0),							\n"
	"							eye	);												\n"
	"																				\n"
	"																				\n"
	"		const vec4 colors[] = vec4[3]( vec4(1.0, 0.0, 0.0, 1.0),				\n"
	"										vec4(0.0, 1.0, 0.0, 1.0),				\n"
	"										vec4(0.0, 0.0, 1.0, 1.0));				\n"
	"																				\n"
	"		gl_Position = eye_mat * (vertices[gl_VertexID]); //+ offset);							\n"
	"																				\n"
	"		vs_color = colors[gl_VertexID];											\n"
	"	}																			\n"
};